# Worksheet 10

You are encouraged to work in groups of up to 3 total students, but each student should make their own submission on Canvas.  (It's fine for everyone in the group to have the same upload.)

Put the **full names** of everyone in your group (even if you're working alone) here.  (This makes grading easier.)

* **Names**: Seth Abuhamdeh

## Part 1: Predicting MPG using one feature

* Load the *mpg* dataset from Seaborn and store it with the variable name `df`.

In [1]:
import pandas as pd

In [2]:
import seaborn as sns

In [3]:
import altair as alt

In [4]:
df = sns.load_dataset("mpg")

In [5]:
df

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model_year  origin                       name  
0            70     usa  chevrolet chevelle malibu  
1            70     usa          buick skylark 320  
2            70     usa         plymouth satellite  
3            70     usa              amc rebel sst  
4            70     usa                ford torino  
..          ...     ...                        ...  
393          82     usa            ford mustang gl  
394          82  europe                  vw pickup  
395          82     usa              dodge rampage  
396          82     usa                ford ranger  
397          82     usa                 chevy s-10  

[398 rows x 9 columns]

* Drop the rows that contain missing values from the dataset, using `df.dropna(axis=???)`.  Save the resulting DataFrame also as `df`, either using `df = df.dropna(axis=???)` or by using `df.dropna(axis=???, inplace=???)` (no `df=` in this second one).

In [6]:
df = df.dropna(axis = 0)

* Using Altair, make a scatter plot with "horsepower" along the x-axis and with "mpg" along the y-axis.

In [7]:
alt.Chart(df).mark_circle().encode(
    x = "horsepower",
    y = "mpg"

)

alt.Chart(...)

Based on this chart, answer the following questions in a markdown cell.

1. In a line of best fit $\text{mpg} \approx m \cdot \text{horsepower} + b$, based on the above chart, what would you estimate for $m$ and $b$?  (Just a rough estimate is fine.)

2.  In particular, does the chart suggest $m$ is positive or negative?  Does that make sense intuitively, from the real-world meaning of this data?

3.  Does a straight line seem to be a good fit for this data?  Write about one sentence giving your opinion.  (I don't think there is a clear correct answer for this, just tell me how it seems to you.)

Be sure you are answering in a markdown cell, not in a Python comment.

1. m = -0.25, b = 75
2. m is negative, yes as cars burn more gas when the engine is more powerful
3.no, it seems the curve is logarithmic thus mpg remains roughly the same with very powerful cars. 

* Find values of $m$ and $b$ (in the notation above) using the `LinearRegression` class from `sklearn.linear_model`.  Assign these values to variables `m` and `b`.

In [8]:
from sklearn.linear_model import LinearRegression

In [9]:
reg = LinearRegression()

In [10]:
reg.fit(df[["horsepower"]], df["mpg"])

LinearRegression()

In [11]:
m = reg.coef_
m

array([-0.15784473])

In [12]:
b = reg.intercept_
b

39.93586102117047

In [13]:
reg.intercept_

39.93586102117047

* Verify that `m` is actually a float, not a NumPy array, using `type`.  If not, then fix it.

Hint.  If `arr` is a NumPy array containing just a single element in it, you can access that single element using the `item` method.  Or you could just use `arr[0]`.

In [14]:
type(m)

numpy.ndarray

In [15]:
m = m[0]
m


-0.15784473335365365

In [16]:
type(m)

numpy.float64

## Part 2: Predicting MPG using multiple features

Now we will use four input variables rather than just one.

* Define a list `pred_cols` containing the names of the four input columns we will use.
```
pred_cols = ["horsepower", "weight", "model_year", "cylinders"]
```

In [17]:
pred_cols = ["horsepower", "weight", "model_year", "cylinders"]

* Fit a new `LinearRegression` object using these four columns as input features and again using "mpg" as the target value.  Store the resulting `LinearRegression` object with the variable name `reg2`.

In [18]:
reg2 = LinearRegression()

In [19]:
reg2.fit(df[pred_cols], df["mpg"])

LinearRegression()

* Evaluate `reg2.coef_`.  It is a little annoying that we can't immediately tell which number corresponds to which variable.

In [20]:
reg2.coef_

array([-0.00361502, -0.00627463,  0.74663191, -0.1276871 ])

* Here is a nice way to group the feature names with the values in a pandas Series.  Execute the following code, after filling in an appropriate value for the `index`.
```
ser = pd.Series(reg2.coef_, index=???)
```
I'm expecting you to use `pred_cols`, but another option that might be more reliable is to use `reg2.feature_names_in_`.

In [21]:
ser = pd.Series(reg2.coef_, index = pred_cols)

In [22]:
ser

horsepower   -0.003615
weight       -0.006275
model_year    0.746632
cylinders    -0.127687
dtype: float64

In [23]:
ser2 = pd.Series(reg2.intercept_, index = pred_cols)

In [24]:
ser2

horsepower   -13.523278
weight       -13.523278
model_year   -13.523278
cylinders    -13.523278
dtype: float64

Examine the pandas Series you made above and answer the following questions in a markdown cell.

1. Only one of the four coefficients is positive.  Explain why it makes sense that particular coefficient is positive, in terms of the real-world meaning of this data.

2. Imagine a car from 1999 weighing 3800 pounds, with 200 horsepower, and with 4 cylinders.  What would our model estimate for the mpg for this car?  (Hint 1.  Notice that a year like `1974` is not written as `1974` in the DataFrame, so don't use `1999` as one of your inputs.  Hint 2.  Don't forget the bias/intercept.)

3.  The horsepower coefficient you computed is quite different from the one computed in Part 1.  Why are these numbers so different?  (Idea: In Part 1, we are learning how mpg changes when horsepower increases.  In this part, we are learning how mpg changes when horsepower increases **and** these other values stay fixed.  Why would you expect that to make a difference?)

1. Newer cars with a greater model year are likely to have better technology yeilding in better mpg performance
2. According to our fit, the estimate for this model is about 35 mpg
3. These values are different since in the first part we don't account for how other variables like model year may affect mpg(for ex. newer cars generally have higher horsepower than older cars and from 1 we have newer cars are generally more gas efficient thus we get 2 variables increasing mpg), but in the second part we fix some of these variables therefore they don't have an effect on mpg, only horsepower does. 

## Part 3: Estimating MPG for a hypothetical car

We will check if your computation above was correct for the 1999 car.

* Define `ser` to be a copy of the top row of `df`.  (In other words, get the top row of `df` however you normally would, and then call `.copy()` at the end of your code.  This way, you can make changes to this Series without affecting `df`.) 

In [25]:
ser = df.iloc[0].copy()

In [26]:
ser

mpg                                  18.0
cylinders                               8
displacement                        307.0
horsepower                          130.0
weight                               3504
acceleration                         12.0
model_year                             70
origin                                usa
name            chevrolet chevelle malibu
Name: 0, dtype: object

* Define a length-4 Python dictionary `dct` with keys "weight", "cylinders", "horsepower", and "model_year" and with values matching what was used in the "imagine a car" question above.  For example,
```
dct = {"weight": 3800, ...}
```

In [27]:
dct = {"weight" : 3800, "cylinders" : 4, "horsepower" : 200, "model_year": 99}

* Call the `update` method of `ser` and pass it `dct` as an argument.

In [28]:
ser.update(dct)

* Evaluate `ser`.  Notice that the values have been changed to match our hypothetical car.

In [29]:
ser

mpg                                  18.0
cylinders                             4.0
displacement                        307.0
horsepower                          200.0
weight                             3800.0
acceleration                         12.0
model_year                           99.0
origin                                usa
name            chevrolet chevelle malibu
Name: 0, dtype: object

* Make a length-1 list whose only element is the pandas Series `ser`.

In [30]:
mylist =  [ser]

In [31]:
mylist

[mpg                                  18.0
 cylinders                             4.0
 displacement                        307.0
 horsepower                          200.0
 weight                             3800.0
 acceleration                         12.0
 model_year                           99.0
 origin                                usa
 name            chevrolet chevelle malibu
 Name: 0, dtype: object]

* Pass that length-1 list to `pd.DataFrame` to construct a one row DataFrame. Assign the result to the variable `df2`.

In [32]:
df2 = pd.DataFrame(mylist)

* Evaluate `df2`.  You should see a length-1 DataFrame, with values matching those of our hypothetical car (and some leftover columns from the original row).

In [33]:
df2

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0        4.0         307.0       200.0  3800.0          12.0   

   model_year origin                       name  
0        99.0    usa  chevrolet chevelle malibu

* Use `reg2.predict` to find the predicted mpg corresponding to this hypothetical car.

Hint.  Remember that we are only using the columns from the list `pred_cols`.

In [34]:
reg2.predict(df2[pred_cols])

array([35.31593774])

* What error message do we get if you try to do the same thing but using `ser[pred_cols]` instead of `df2[pred_cols]`?

In [35]:
reg2.predict(ser[pred_cols])

/shared-libs/python3.9/py/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


ValueError: Expected 2D array, got 1D array instead:
array=[ 200. 3800.   99.    4.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

* What does the error message mean by "2D array" vs "1D array" in the context of these pandas objects?  Answer in a markdown cell.

A 2D array has both columns and rows to account for meanwhile a 1D array only has rows. Rows can be seen as x values, with columns as y values. Series only have rows, no columns thus is 1 dimensional, Dataframes have columns and rows thus 2 dimensional. 

## Submission

* Reminder: everyone needs to make a submission on Canvas.
* Reminder: Use markdown cells for text explanations, not Python comments.  The only exception is if it is a very brief explanation at the top of a code cell.
* Reminder: include everyone's full name at the top, after **Names**.
* Using the `Share` button at the top right, enable public sharing, and enable Comment privileges. Then submit the created link on Canvas.

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=27844981-221f-42a0-b142-ef6721330937' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>