# Worksheet 13

You are encouraged to work in groups of up to 3 total students, but each student should make their own submission on Canvas.  (It's fine for everyone in the group to have the same upload.)

Put the **full names** of everyone in your group (even if you're working alone) here.  (This makes grading easier.)

* **Names**: Seth Abuhamdeh

## Introduction

Our goal in this worksheet is to predict whether the species of a penguin is Adelie using its bill length as our only input feature.

In [1]:
import altair as alt
import pandas as pd
import seaborn as sns
import numpy as np

* Import the *penguins* dataset from Seaborn, drop the rows in which the "bill_length_mm" column contains missing data, and save the resulting it in the variable name `df`.  (Hint.  I don't see a way to do this using `dropna`.  I recommend using Boolean indexing together with the `isna` method and negation `~` or else with the `notna` method.  Call the `copy` method when you perform the Boolean indexing, to prevent warnings below.)

* Check your answer.  The DataFrame should have `342` rows.

In [2]:
df = sns.load_dataset("penguins")

In [3]:
df

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
2    Adelie  Torgersen            40.3           18.0              195.0   
3    Adelie  Torgersen             NaN            NaN                NaN   
4    Adelie  Torgersen            36.7           19.3              193.0   
..      ...        ...             ...            ...                ...   
339  Gentoo     Biscoe             NaN            NaN                NaN   
340  Gentoo     Biscoe            46.8           14.3              215.0   
341  Gentoo     Biscoe            50.4           15.7              222.0   
342  Gentoo     Biscoe            45.2           14.8              212.0   
343  Gentoo     Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  
0         3750.0    Male  
1         3800.0  Female  
2         3250.0  Female  
3            NaN     NaN  
4         3450.0  Female  
..           ...     ...  
339          NaN     NaN  
340       4850.0  Female  
341       5750.0    Male  
342       5200.0  Female  
343       5400.0    Male  

[344 rows x 7 columns]

In [4]:
df = df[~df["bill_length_mm"].isna()]

In [5]:
df

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
2    Adelie  Torgersen            40.3           18.0              195.0   
4    Adelie  Torgersen            36.7           19.3              193.0   
5    Adelie  Torgersen            39.3           20.6              190.0   
..      ...        ...             ...            ...                ...   
338  Gentoo     Biscoe            47.2           13.7              214.0   
340  Gentoo     Biscoe            46.8           14.3              215.0   
341  Gentoo     Biscoe            50.4           15.7              222.0   
342  Gentoo     Biscoe            45.2           14.8              212.0   
343  Gentoo     Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  
0         3750.0    Male  
1         3800.0  Female  
2         3250.0  Female  
4         3450.0  Female  
5         3650.0    Male  
..           ...     ...  
338       4925.0  Female  
340       4850.0  Female  
341       5750.0    Male  
342       5200.0  Female  
343       5400.0    Male  

[342 rows x 7 columns]

* Add a new column to `df` called "isAdelie_bool" which contains `True` if the species is "Adelie" and which contains `False` otherwise.

In [6]:
df["isAdelie_bool"]= df["species"] == "Adelie"

/tmp/ipykernel_140/4219436481.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["isAdelie_bool"]= df["species"] == "Adelie"


* Add a new column to `df` called "isAdelie" which contains `1` if the species is "Adelie" and which contains `0` otherwise.  (Suggestion.  Call the `astype` method on the "isAdelie_bool" column and specify that the values should be converted to integers.)

In [7]:
df["isAdelie"] = df["isAdelie_bool"].astype(int)

/tmp/ipykernel_140/2952418812.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["isAdelie"] = df["isAdelie_bool"].astype(int)


* Using Altair, draw a scatter plot encoding the "bill_length_mm" column in the x-axis channel and encoding "isAdelie" in the y-axis channel.  Store the resulting chart with the variable name `c`.

In [8]:
c = alt.Chart(df).mark_circle().encode(
    x = "bill_length_mm",
    y = "isAdelie"
)

In [9]:
c

alt.Chart(...)

## Why not use linear regression?

* Fit a `LinearRegression` object to this data, using "bill_length_mm" as the only input feature, and using "isAdelie" as the target.

In [10]:
from sklearn.linear_model import LinearRegression

In [11]:
reg = LinearRegression()

In [12]:
reg.fit(df[["bill_length_mm"]], df["isAdelie"])

LinearRegression()

* Add a column "pred_lin" to the DataFrame containing the predicted outputs from this linear regression model (the inputs should still be the "bill_length_mm" column).

In [13]:
df["pred_lin"] = reg.predict(df[["bill_length_mm"]])

/tmp/ipykernel_140/92268701.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["pred_lin"] = reg.predict(df[["bill_length_mm"]])


* Make a new Altair chart `c2`, this time a line chart, using "bill_length_mm" for the x-axis channel and using "pred_lin" for the y-axis channel.  Draw the line in the color "red".

In [14]:
c2 = alt.Chart(df).mark_line(color = "red").encode(
    x = "bill_length_mm",
    y = "pred_lin"
)

* Display `c2` layered on top of `c` from above.

In [15]:
c2 + c

alt.LayerChart(...)

## Using logistic regression

* Fit a `LogisticRegression` object to this same data.  (Don't name the object `reg`.  Name it `clf` instead, for "classifier".)

In [16]:
from sklearn.linear_model import LogisticRegression

In [17]:
clf = LogisticRegression()

In [18]:
clf.fit(df[["bill_length_mm"]], df["isAdelie"])

LogisticRegression()

* Add a new column to `df` named "pred_log" which contains the predictions corresponding to `clf`.

In [19]:
df["pred_log"] = clf.predict(df[["bill_length_mm"]])

/tmp/ipykernel_140/821203396.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["pred_log"] = clf.predict(df[["bill_length_mm"]])


* Make a new Altair chart `c3`, this time back to being a scatter plot, using "bill_length_mm" for the x-axis channel and using "pred_log" for the y-axis channel.  Draw the points in the color "red".

In [20]:
c3 = alt.Chart(df).mark_circle(color = "red").encode(
    x = "bill_length_mm",
    y = "pred_log"
)

* Display `c3` layered on top of `c` from above.

In [21]:
c3 + c

alt.LayerChart(...)

## Assessing the accuracy

What proportion of these predicted values are correct?  We will check this two different ways.

* What proportion (as a float between 0 and 1) of the values predicted by logistic regression are correct?  You should not use `clf` to answer this question, just compare the "isAdelie" column to the "pred_log" column.

**Caution**.  If you find yourself using a for-loop or list comprehension or anything like that, you should look for a more succinct approach.  Make a Boolean Series and call the `mean` method.

In [36]:
(df["isAdelie"] == df["pred_log"]).mean()

0.9444444444444444

* Now call the `score` method of `clf`, and input the input features along with the true outputs.  You should get the same number as above (up to maybe some small numerical precision issues).

In [37]:
clf.score(df[["bill_length_mm"]], df["isAdelie"])

0.9444444444444444

## Probabilities

* Call the `predict_proba` method of `clf`, using the same input features as above.  This will report the predicted probabilities.  Name the result `arr`.

In [38]:
arr = clf.predict_proba(df[["bill_length_mm"]])

In [39]:
arr

array([[1.22106209e-02, 9.87789379e-01],
       [1.92980037e-02, 9.80701996e-01],
       [4.74948499e-02, 9.52505150e-01],
       [7.59157675e-04, 9.99240842e-01],
       [1.53568877e-02, 9.84643112e-01],
       [9.70259869e-03, 9.90297401e-01],
       [1.36949402e-02, 9.86305060e-01],
       [3.70069410e-05, 9.99962993e-01],
       [2.64508687e-01, 7.35491313e-01],
       [2.72087661e-03, 9.97279123e-01],
       [2.72087661e-03, 9.97279123e-01],
       [1.12178289e-01, 8.87821711e-01],
       [6.86600051e-03, 9.93133999e-01],
       [6.61679891e-05, 9.99933832e-01],
       [6.75915930e-04, 9.99324084e-01],
       [7.70569760e-03, 9.92294302e-01],
       [3.91373088e-01, 6.08626912e-01],
       [5.24448601e-05, 9.99947555e-01],
       [9.74075469e-01, 2.59245308e-02],
       [2.72087661e-03, 9.97279123e-01],
       [2.42305371e-03, 9.97576946e-01],
       [2.99728306e-04, 9.99700272e-01],
       [4.32426176e-03, 9.95675738e-01],
       [8.64719370e-03, 9.91352806e-01],
       [1.492588

* What is the type of the output of `predict_proba`?  What is the shape of the output?

In [40]:
arr.shape

(342, 2)

In [42]:
type(arr[1,1])

numpy.float64

In [43]:
type(arr)

numpy.ndarray

* What is the row at index `8` of `arr`?

In [44]:
arr[8]

array([0.26450869, 0.73549131])

* This means our model predicts there is about a 26% chance the penguin is something, and about a 74% chance it is not.  But which number corresponds to which?  Use the `classes_` attribute of `clf` to decide which is which.

In [45]:
clf.classes_

array([0, 1])

* Can you calculate one of these values explicitly using the sigmoid function $1/(1+e^{-x})$?  You will need to use the fit coefficient and intercept from `clf` along with the input value corresponding to the row and integer location `8` in `df`.

In [46]:
df.iloc[8]["bill_length_mm"]

42.0

In [47]:
clf.intercept_

array([49.83678412])

In [48]:
clf.coef_

array([[-1.16224094]])

In [49]:
1/(1+np.exp(-(49.83678412-1.16224094*42.0)))

0.7354913139533407

* Extract the column of `arr` corresponding to the probability that the penguin is an Adelie species.  Store this in a new column of `df` named "pred_proba".

In [51]:
df["pred_proba"] = arr[:,1]

/tmp/ipykernel_140/1810565323.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["pred_proba"] = arr[:,1]


In [52]:
df.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
4  Adelie  Torgersen            36.7           19.3              193.0   
5  Adelie  Torgersen            39.3           20.6              190.0   

   body_mass_g     sex  isAdelie_bool  isAdelie  pred_lin  pred_log  \
0       3750.0    Male           True         1  0.809046         1   
1       3800.0  Female           True         1  0.778558         1   
2       3250.0  Female           True         1  0.717582         1   
4       3450.0  Female           True         1  0.991973         1   
5       3650.0    Male           True         1  0.793802         1   

   pred_proba  
0    0.987789  
1    0.980702  
2    0.952505  
4    0.999241  
5    0.984643

* Make a new Altair line chart `c4`, using the color red, and with "bill_length_mm" for the x-axis and with "pred_proba" for the y-axis.

In [53]:
c4 = alt.Chart(df).mark_line(color ="red").encode(
    x = "bill_length_mm",
    y = "pred_proba"
)

* Layer this chart on top of `c` from above.

In [54]:
c + c4

alt.LayerChart(...)

* If you wanted to locate the penguin from the row at integer location `8` in the above plot, how would you try to do that?  Briefly answer in a markdown cell (not in a Python comment).

since we know that the penguin at integer location 8 has bill length 42, we can look at x = 42, according the our graph it would appear that it's likely at value 1 or that it's an adelie penguin

* Briefly explain in your own words, in terms of the above plots, why does logistic regression seem more natural to use for this task than linear regression?  (Your answer should make reference to something about how these charts look.  Using 1-2 sentences is enough.)

Linear regression gives a straight diagonal line for points that only have 2 values thus the linear regression line only goes through a few points and doesn't represent the dat very well. Logistical regression uses a steep curved line thus represents that data much better and hits more points.

## Submission

* Reminder: everyone needs to make a submission on Canvas.
* Reminder: include everyone's full name at the top, after **Names**.
* Using the `Share` button at the top right, enable public sharing, and enable Comment privileges. Then submit the created link on Canvas.

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=472be44f-8fe2-4a9d-bcff-b9502f8002ab' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>